heat_template_version: 2013-05-23

description: Create Volume

resources:
  my_instance:
    type: OS::Nova::Server
    properties:
      image: cirros-0.3.4-x86_64-uec
      flavor: m1.tiny
      networks:
        - network: private

  my_vol:
    type: OS::Cinder::Volume
    properties:
      size: 1
      name: vol

  attach_vm:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_resource: my_instance }
      volume_id: { get_resource: my_vol }
